# Generated by Django 6.0.5 on 2026-05-20 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='allowed_domains',
        ),
        migrations.RemoveField(
            model_name='site',
            name='filter_allowed_domains',
        ),
    ]
